In [2]:
import numpy as np
import cv2

In [3]:
def S_red():
    img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
    mask = np.array([[0, -1, 0],[-1, 5, -1],[0, -1, 0]])
    img = img[:,:,0] #768 1241 3
    img_height = img.shape[0]
    img_width = img.shape[1]
    mask_height = mask.shape[0] #mask[3x3]
    mask_width = mask.shape[1]
    H = (mask_height - 1) // 2 #H, W = (1, 1)
    W = (mask_width - 1) // 2
    out = np.zeros((img_height, img_width))
    for i in np.arange(H, img_height - H):
        for j in np.arange(W, img_width - W):
            sum = 0
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    a = img[i + k, j + l]
                    w = mask[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum 
            #out[1:img_height - H , 1: img_width - W] xoa duong 0 ben ngoai
    return out.astype(np.uint8)
print(S_red())
img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
print(img[:,:,0])
print(np.add(S_red(), img[:,:,0]))

[[  0   0   0 ...   0   0   0]
 [  0  17  14 ...   6   7   0]
 [  0  10  11 ...   6   9   0]
 ...
 [  0 237   4 ... 111  65   0]
 [  0 252  24 ... 107  47   0]
 [  0   0   0 ...   0   0   0]]
[[15 12 11 ...  7  9 11]
 [15 14 13 ...  7  8  9]
 [13 13 13 ...  7  8  8]
 ...
 [38 12 11 ... 90 76 72]
 [43 18 18 ... 87 73 76]
 [46 21 21 ... 89 79 75]]
[[ 15  12  11 ...   7   9  11]
 [ 15  31  27 ...  13  15   9]
 [ 13  23  24 ...  13  17   8]
 ...
 [ 38 249  15 ... 201 141  72]
 [ 43  14  42 ... 194 120  76]
 [ 46  21  21 ...  89  79  75]]


In [5]:
def S_green():
    img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
    mask = np.array([[0, -1, 0],[-1, 5, -1],[0, -1, 0]])
    img = img[:,:,1] #768 1241 3
    img_height = img.shape[0]
    img_width = img.shape[1]
    mask_height = mask.shape[0] #mask[3x3]
    mask_width = mask.shape[1]
    H = (mask_height - 1) // 2 #H, W = (1, 1)
    W = (mask_width - 1) // 2
    out = np.zeros((img_height, img_width))
    for i in np.arange(H, img_height - H):
        for j in np.arange(W, img_width - W):
            sum = 0
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    a = img[i + k, j + l]
                    w = mask[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum
    #out[1:img_height - H , 1: img_width - W] xoa duong 0 ben ngoai
    return out.astype(np.uint8)
print(S_green())
img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
print(img[:,:,1])
print(np.add(S_green(), img[:,:,1]))

[[  0   0   0 ...   0   0   0]
 [  0  34  31 ...  20  24   0]
 [  0  33  34 ...  20  23   0]
 ...
 [  0 243  16 ... 139  83   0]
 [  0   2  30 ... 131  79   0]
 [  0   0   0 ...   0   0   0]]
[[ 34  31  30 ...  21  23  22]
 [ 34  33  32 ...  21  22  20]
 [ 34  34  34 ...  21  22  22]
 ...
 [ 41  18  21 ... 112  95  86]
 [ 49  25  28 ... 111  97  95]
 [ 52  28  34 ... 115 105  97]]
[[ 34  31  30 ...  21  23  22]
 [ 34  67  63 ...  41  46  20]
 [ 34  67  68 ...  41  45  22]
 ...
 [ 41   5  37 ... 251 178  86]
 [ 49  27  58 ... 242 176  95]
 [ 52  28  34 ... 115 105  97]]


In [6]:
def S_blue():
    img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
    mask = np.array([[0, -1, 0],[-1, 5, -1],[0, -1, 0]])
    img = img[:,:,2] #768 1241 3
    img_height = img.shape[0]
    img_width = img.shape[1]
    mask_height = mask.shape[0] #mask[3x3]
    mask_width = mask.shape[1]
    H = (mask_height - 1) // 2 #H, W = (1, 1)
    W = (mask_width - 1) // 2
    out = np.zeros((img_height, img_width))
    for i in np.arange(H, img_height - H):
        for j in np.arange(W, img_width - W):
            sum = 0
            for k in np.arange(-H, H + 1):
                for l in np.arange(-W, W + 1):
                    a = img[i + k, j + l]
                    w = mask[H + k, W + l]
                    sum += (w * a)
            out[i, j] = sum
   #out[1:img_height - H , 1: img_width - W] xoa duong 0 ben ngoai
    return out.astype(np.uint8)
print(S_blue())
img = cv2.cvtColor(cv2.imread("GreenVietnam.png"), cv2.COLOR_BGR2RGB)
print(img[:,:,2])
print(np.add(S_blue(), img[:,:,2]))

[[  0   0   0 ...   0   0   0]
 [  0  33  30 ...  22  25   0]
 [  0  23  24 ...  19  22   0]
 ...
 [  0 246 250 ...  53   2   0]
 [  0 238   4 ...  47 242   0]
 [  0   0   0 ...   0   0   0]]
[[30 27 26 ... 22 24 24]
 [30 29 28 ... 22 23 22]
 [27 27 27 ... 21 22 22]
 ...
 [10  0  0 ... 27 14 11]
 [15  0  3 ... 23 11 14]
 [16  0  6 ... 24 18 14]]
[[ 30  27  26 ...  22  24  24]
 [ 30  62  58 ...  44  48  22]
 [ 27  50  51 ...  40  44  22]
 ...
 [ 10 246 250 ...  80  16  11]
 [ 15 238   7 ...  70 253  14]
 [ 16   0   6 ...  24  18  14]]


In [11]:
r = S_red()
g = S_green()
b = S_blue()
S = cv2.merge([b, g, r])
print(S)

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [ 33  34  17]
  [ 30  31  14]
  ...
  [ 22  20   6]
  [ 25  24   7]
  [  0   0   0]]

 [[  0   0   0]
  [ 23  33  10]
  [ 24  34  11]
  ...
  [ 19  20   6]
  [ 22  23   9]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [246 243 237]
  [250  16   4]
  ...
  [ 53 139 111]
  [  2  83  65]
  [  0   0   0]]

 [[  0   0   0]
  [238   2 252]
  [  4  30  24]
  ...
  [ 47 131 107]
  [242  79  47]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [15]:
cv2.imshow("S", S)
cv2.waitKey(0)

-1